services:
  postgres:
    image: postgres:18-alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgresql://postgres:${POSTGRES_PASSWORD}@localhost:5432"]
      interval: 1s
      timeout: 10s
      retries: 30
    networks:
      - xrates-network

  redis:
    image: redis:8-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"
    healthcheck:
      test: ["CMD", "redis-cli","--pass","${REDIS_PASSWORD}","ping",]
      interval: 1s
      timeout: 10s
      retries: 30
    networks:
      - xrates-network

  backend:
    build:
      context: Xrates
      dockerfile: ../backend.Dockerfile
    ports:
      - "80:8080"
    environment:
      - ConnectionStrings__Postgres=Host=postgres;Port=5432;Database=postgres;Username=postgres;Password=${POSTGRES_PASSWORD}
      - ConnectionStrings__Redis=redis:6379,password=${REDIS_PASSWORD}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - xrates-network


volumes:
  postgres-data:
  redis-data:

networks:
  xrates-network:
    driver: bridge
